# Generated by Django 4.2.6 on 2023-12-02 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, max_length=50, null=True)),
                ('lname', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phoneno', models.BigIntegerField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Contactus',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=128)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'country',
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phoneno', models.BigIntegerField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'inquiry',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'service',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=50)),
                ('amount', models.BigIntegerField()),
                ('status', models.CharField(max_length=50)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visapp.service')),
                ('user_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'payment',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('australia', 'australia'), ('canada', 'canada'), ('europe', 'europe'), ('newzeland', 'newzeland'), ('singapore', 'singapore')], max_length=20)),
                ('visatype', models.CharField(choices=[('business', 'business'), ('work', 'work'), ('tourist', 'tourist'), ('student', 'student')], max_length=20)),
                ('passport', models.FileField(upload_to='')),
                ('photo', models.FileField(upload_to='')),
                ('bankstatement', models.FileField(upload_to='')),
                ('itr', models.FileField(blank=True, null=True, upload_to='')),
                ('hotelconfirm', models.FileField(blank=True, null=True, upload_to='')),
                ('employeeproof', models.FileField(blank=True, null=True, upload_to='')),
                ('jobproof', models.FileField(blank=True, null=True, upload_to='')),
                ('propertyproof', models.FileField(upload_to='')),
                ('investment', models.FileField(blank=True, null=True, upload_to='')),
                ('leaveletter', models.FileField(blank=True, null=True, upload_to='')),
                ('APD', models.FileField(upload_to='')),
                ('accommodation', models.FileField(blank=True, null=True, upload_to='')),
                ('marriagecerti', models.FileField(blank=True, null=True, upload_to='')),
                ('childrenproof', models.FileField(blank=True, null=True, upload_to='')),
                ('user_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Document',
            },
        ),
        migrations.CreateModel(
            name='Clientprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.BigIntegerField()),
                ('date_of_birth', models.DateField()),
                ('current_education', models.CharField(choices=[('below 12', 'below 12'), ('12', '12'), ('diploma', 'diploma'), ('graduate', 'graduate'), ('masters', 'masters')], max_length=20)),
                ('IELTSAppeared', models.BooleanField()),
                ('user_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'clientprofile',
            },
        ),
        migrations.CreateModel(
            name='Adviserprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.BigIntegerField()),
                ('date_of_birth', models.DateField()),
                ('experience', models.FloatField()),
                ('qualification', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=50)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visapp.service')),
                ('user_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Adviserprofile',
            },
        ),
    ]
