# Generated by Django 4.2.6 on 2023-12-02 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='IELTSAppeared',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='current_education',
            field=models.CharField(blank=True, choices=[('below 12', 'below 12'), ('12', '12'), ('diploma', 'diploma'), ('graduate', 'graduate'), ('masters', 'masters')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
