# Generated by Django 4.2.6 on 2024-02-21 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visapp', '0002_alter_clientprofile_ieltsappeared_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adviserprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='adviserprofile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='adviserprofile',
            name='service',
        ),
        migrations.AddField(
            model_name='adviserprofile',
            name='visatype',
            field=models.CharField(choices=[('business', 'business'), ('work', 'work'), ('tourist', 'tourist'), ('student', 'student')], default='student visa', max_length=20),
        ),
    ]
