# Generated by Django 4.2.6 on 2024-02-22 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visapp', '0004_adviserprofile_email_adviserprofile_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adviserprofile',
            name='user_model',
        ),
    ]
